grav: displist.c force.c getArrayIndex.c intVec.c omelyan.c parentChild.c planetListFunctions.c populateRegions.c poster_recover.c resetregion.c vector.c wellSepCoM.c timing.c 
	g++ displist.c force.c getArrayIndex.c intVec.c omelyan.c parentChild.c planetListFunctions.c populateRegions.c poster_recover.c resetregion.c vector.c wellSepCoM.c timing.c -lm -o grav -O4
